"""
Example: Transform an existing PowerPoint file into a reusable template.

This script demonstrates how to:
- Upload a .pptx file to the /api/v1/transform endpoint
- Save the resulting template (stored in the database)
- List all available templates to confirm the upload
- Use that template ID when generating a new presentation

Requirements:
    pip install requests

Usage:
    python examples/transform_ppt.py path/to/your_presentation.pptx

If no path is provided, the script creates a minimal sample .pptx for demonstration.
"""

import os
import sys
import tempfile
import requests

BASE_URL = os.environ.get("PPT_API_URL", "http://localhost:8000")


def create_sample_pptx(output_path: str) -> None:
    """Create a minimal sample .pptx file for demonstration purposes."""
    try:
        from pptx import Presentation
        from pptx.util import Inches, Pt
    except ImportError:
        print("python-pptx is required to create a sample file.")
        print("Install it with: pip install python-pptx")
        sys.exit(1)

    prs = Presentation()
    slide_layout = prs.slide_layouts[0]  # Title slide
    slide = prs.slides.add_slide(slide_layout)
    slide.shapes.title.text = "Sample Presentation"
    slide.placeholders[1].text = "Generated by ppt-generator example"
    prs.save(output_path)
    print(f"Created sample file: {output_path}")


def transform_pptx(file_path: str, name: str, description: str = "") -> dict:
    """Upload a .pptx file to the /api/v1/transform endpoint."""
    with open(file_path, "rb") as f:
        response = requests.post(
            f"{BASE_URL}/api/v1/transform",
            files={"file": (os.path.basename(file_path), f, "application/vnd.openxmlformats-officedocument.presentationml.presentation")},
            data={"name": name, "description": description},
            timeout=120,
        )
    response.raise_for_status()
    return response.json()


def list_templates() -> dict:
    """Fetch all templates from the /api/v1/templates endpoint."""
    response = requests.get(f"{BASE_URL}/api/v1/templates", timeout=30)
    response.raise_for_status()
    return response.json()


def generate_with_template(prompt: str, template_id: str, slide_count: int = 5) -> dict:
    """Generate a presentation using a specific template."""
    response = requests.post(
        f"{BASE_URL}/api/v1/generate",
        json={
            "prompt": prompt,
            "template_id": template_id,
            "slide_count": slide_count,
        },
        timeout=120,
    )
    response.raise_for_status()
    return response.json()


def main() -> None:
    # --- Step 1: Determine the source .pptx file ---
    created_temp = False
    if len(sys.argv) > 1:
        pptx_path = sys.argv[1]
        if not os.path.isfile(pptx_path):
            print(f"File not found: {pptx_path}")
            sys.exit(1)
    else:
        tmp_file = tempfile.NamedTemporaryFile(suffix=".pptx", delete=False)
        pptx_path = tmp_file.name
        tmp_file.close()
        created_temp = True
        print("No file provided — creating a sample .pptx for demonstration...")
        create_sample_pptx(pptx_path)

    try:
        # --- Step 2: Transform the .pptx into a template ---
        print(f"\nUploading and transforming: {pptx_path}")
        template = transform_pptx(
            file_path=pptx_path,
            name="My Uploaded Template",
            description="Transformed from an existing .pptx file",
        )
    finally:
        if created_temp and os.path.exists(pptx_path):
            os.remove(pptx_path)

    print(f"Template ID   : {template['id']}")
    print(f"Template name : {template['name']}")
    print(f"Slide count   : {template['slide_count']}")
    print(f"Created at    : {template['created_at']}")

    # --- Step 3: List all templates ---
    print("\nAll stored templates:")
    all_templates = list_templates()
    for t in all_templates["templates"]:
        print(f"  - [{t['id']}] {t['name']} ({t['slide_count']} slides)")
    print(f"Total: {all_templates['total']}")

    # --- Step 4: Generate a new presentation using the uploaded template ---
    print(f"\nGenerating a presentation using template '{template['name']}'...")
    presentation = generate_with_template(
        prompt="Create a quarterly business review presentation with key metrics and highlights.",
        template_id=template["id"],
        slide_count=5,
    )

    print(f"Presentation ID  : {presentation['id']}")
    print(f"Filename         : {presentation['filename']}")
    print(f"Download URL     : {presentation['download_url']}")
    print("\nDone!")


if __name__ == "__main__":
    main()
